### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [anuragxel/salt#12]
Hi
Thanks for your quick and great job!

I want to test on 3 images but get the following error when calling segment_anything_annotator.py
any insights?
 
`
Traceback (most recent call last):
  File "segment_anything_annotator.py", line 26, in <module>
    editor = Editor(
  File "/mnt/data/polymore/salt/salt/editor.py", line 57, in __init__
    ) = self.dataset_explorer.get_image_data(self.image_id)
  File "/mnt/data/polymore/salt/salt/dataset_explorer.py", line 146, in get_image_data
    image_name = self.coco_json["images"][image_id]["file_name"]
IndexError: list index out of range
`

Thanks in advance

**Comment by anuragxel** [comment]
Can you paste the contents of your images folder?

**Comment by SuroshAhmadZobair** [comment]
@Terrylala 
Can you please share the contents of your images dir?
Mine would be a violation of NDA. 

Thanks for you support!

**Comment by adeel-maker** [comment]
I am also facing the same issue!!!

**Comment by Terrylala** [comment]
[Uploading test_image.zip…]()

**Comment by Terrylala** [comment]
[test_image.zip](https://github.com/anuragxel/salt/files/11221730/test_image.zip)

**Comment by anuragxel** [comment]
The dataset should be in the following format. I tried your data and it worked for me.

`<dataset_name>/images/*.jpg`
`<dataset_name>/embeddings/*.npy`

<img width="1352" alt="Screenshot 2023-04-13 at 8 39 21 AM" src="https://user-images.githubusercontent.com/5917609/231760997-a70c1ecd-1fb9-462c-9b53-9dc9409e933d.png">
