### ISSUE TITLE
integrate this with labelstudio

### ISSUE THREAD

**Issue by hemangjoshi37a** [anuragxel/salt#19]
If possible then please integrate this repo with labelstudio because there are lots of other things  that they have got it right.

**Comment by anuragxel** [comment]
There exist many such tools (CVAT is the tool of choice in my lab). Understanding their large codebase and integrating it with their UI elements and flow is a lot of work.

I made this tool in a couple days for my weekly lab meeting. :) This code is MIT licensed, so feel free to borrow elements for labelstudio if you are a core developer.
