### ISSUE TITLE
The mask does not exactly coincide with the original image

### ISSUE THREAD

**Issue by 1191658517** [anuragxel/salt#2]
as the blow image show
![image](https://user-images.githubusercontent.com/54796134/230812541-70e4f037-ae97-4354-b053-6bf915b70c1d.png)

**Comment by anuragxel** [comment]
So this is an artifact of ONNX generator helper. Did you change the resolution of the helper to generate a ONNX model of the resolution of your images?

**Comment by anuragxel** [comment]
I would appreciate a PR that can select the right ONNX model based on the resolution of the input (assuming ONNX model name format maybe -- onnx_model_<res>.onnx).

**Comment by 1191658517** [comment]
Thank you very much for your prompt reply！I use default  resolution of the input as shown blow.
Is there anything that I need to change ?

**Comment by 1191658517** [comment]
![image](https://user-images.githubusercontent.com/54796134/230813277-830ee8ee-7a02-4308-a4b1-4d9578f24efc.png)

**Comment by anuragxel** [comment]
Yeah, change it to the resolution of your input image and try again? It should work. This is how ONNX models work, they compile the model ops to a specified resolution (and usually it works for multiples of that resolution, which your image probably isn't).

**Comment by 1191658517** [comment]
yes it works nicely now.
this issule(https://github.com/facebookresearch/segment-anything/issues/56) has reported this problem either.

**Comment by anuragxel** [comment]
Yeah, this is an ONNX thing. It can be handled at an application level pretty easily (generate all models corresponding to each resolution for a dataset, pick the model based on resolution). I have added #3 enhancement covering this, closing this issue for now.
