### ISSUE TITLE
Select ONNX model depending on the input resolution

### ISSUE THREAD

**Issue by anuragxel** [anuragxel/salt#3]
Models folder would have all onnx models in a specified format e.g. "<prefix>.\<res>\.onnx" and the ONNX caller picks up the "right" model for the given image.

**Comment by Luwill6** [comment]
Thanks for your great work! Can u upload onnx model? i just can't export onnx model on SAM repo

**Comment by anuragxel** [comment]
Will fix this tonight, got a few mails on this. See #2 for current way to fix this.
