### ISSUE TITLE
Some GUI problems

### ISSUE THREAD

**Issue by Levine66** [anuragxel/salt#31]
Thanks for your tools. I am trying to use this tool in my equipment. And i meet some problems during run the segment_anything_annotator.py. 

I have a server with GPU, which is a Linux system without GUI. It's totally  terminal system. I use my Macbook to link the server with SSH tool. And I have created embedding and onnx model in server. 

When I want to annotate my images, the PyQt doesn't work well and export error:Could not connect to any X display and QLibraryPrivate::unload succeeded on "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so". I have tried to fix it by reinstall pyqt and install PYQT Integration in my VSCode. But it is not useful for me.

 I would like to ask two questions:
1. How can i solve my PyQt problems? Can you give me some advices?
2. How to use your tool in Macbook and GPU server more more convenient?

I am looking forward to your answer

**Comment by Levine66** [comment]
Thanks for your reply. I have tried this way after submitting this issues. This works on my  laptop. I had considered that CPU is not fast enough before submitting this issues, and it is totally wrong.  Thanks for your tools again, i would like to use it and make some contribution to this project if possible.

**Comment by anuragxel** [comment]
The SAM paper mentions that their decoder (the ONNX model) was shipped to their annotators. Also their online demo runs the decoder on your browser. I just wrote a tool to do the same thing that their demo does. :)
