### ISSUE TITLE
Support for adding custom model?

### ISSUE THREAD

**Issue by dat-rohit** [anuragxel/salt#54]
Hi, I was looking at this tool and was wondering if (and how) it would be possible to use my own finetuned SAM model instead of the base one?
Ideally, I would like to draw the bounding box and let my model predict a segmented mask.

Any insight or help would be highly appreciated.

**Comment by Skwarson96** [comment]
How did you finetune SAM? Did you use any open solutions?

**Comment by dat-rohit** [comment]
It was actually released here in open-source with a .pth file: https://github.com/OpenGVLab/SAM-Med2D

**Comment by Skwarson96** [comment]
@dat-rohit I read your question once again and I have two observations:
- These labeling tool based on pre generated embeddings and onnx models so you need to figure out how to do it with your model
- SALT doesnt support box labeling :cry:

**Comment by dat-rohit** [comment]
Thank you a lot for your insightful answer, definitely helped me!

**Comment by Skwarson96** [comment]
I added box prompt to my fork [here](https://github.com/Skwarson96/salt)
