### ISSUE TITLE
how can i draw different class?

### ISSUE THREAD

**Issue by Manningchan** [anuragxel/salt#7]
i set 5 classes in it ,but i dont know how to choose these class. it seems no thing happend whether click the class button on the right of the windows

**Comment by anuragxel** [comment]
Can you pull and try now? It was a bug, I think it works now. Thanks!

**Comment by Manningchan** [comment]
> Can you pull and try now? It was a bug, I think it works now. Thanks!

yes，it works and i have another question ，if i add a predict mask，how can i delete it， thanks

**Comment by anuragxel** [comment]
I have not added delete yet. Seems like a couple people want it, I'll add it soon. Closing this issue for now.
