### ISSUE TITLE
Classes Not updated while clicking on the GUI option

### ISSUE THREAD

**Issue by jyothir07** [anuragxel/salt#9]
@anuragxel @Daa98 
I faced this issue when running the app in windows system. The function was not updated with the click event.
```
   def get_side_panel(self):
        panel = QWidget()
        panel_layout = QVBoxLayout(panel)
        categories = self.editor.get_categories()
        for category in categories:
            label = QPushButton(category)
            label.clicked.connect(lambda: self.editor.select_category(category))
            panel_layout.addWidget(label)
        return panel
```
the lambda function inside the loop is capturing the reference to the same category variable every time, and when the lambda function is executed later, it uses the last value that category had in the loop.
To fix this, create a separate function that takes the category as an argument and returns a lambda function that calls _self.editor.select_category(category)_. Now lambda function will capture the value of category at the time it was created.

```
    def get_side_panel(self):
        panel = QWidget()
        panel_layout = QVBoxLayout(panel)
        categories = self.editor.get_categories()
        for category in categories:
            label = QPushButton(category)
            label.clicked.connect(self.create_category_handler(category))
            panel_layout.addWidget(label)
        return panel

    def create_category_handler(self, category):
        return lambda: self.editor.select_category(category)
```

**Comment by anuragxel** [comment]
Can you pull, I have fixed this. Check and let me know.

**Comment by jyothir07** [comment]
> Can you pull, I have fixed this. Check and let me know.

@anuragxel Nice update. It works well now.

**Comment by QuantumLiu** [comment]
@anuragxel Have similar problem in latest version， didn't switch classes after click button

**Comment by anuragxel** [comment]
This was working earlier. I reverted a recent merge, can you try now?
